---
title: "R Notebook"
output: html_notebook
---
```{r message=FALSE, warning=FALSE}
# Visualizing NYPC Compstat data on shootings
# https://data.cityofnewyork.us/Public-Safety/NYPD-Shooting-Incident-Data-Historic-/833y-fsy8

library(tidyverse)
library(lubridate)
library(sf)
# library(sp)
library(mapview)
library(leafpop)
library(ggthemr)
library(ggalluvial) 
ggthemr::ggthemr("dust")
# rev_swatch <- ggthemr:::load_palette.character("solarized")$swatch %>% rev()

shooting_raw <- read_csv("data/NYPD_Shooting_Incident_Data__Historic_.csv")
#View(shooting_raw)
```

```{r}
# -----------------------------------
# clean up data
# make factor levels the same across perp and victim
race_levels <-
   c( "Black",
      "Black Hispanic",
      "White Hispanic",
      "White" ,
      "Asian / Pacific Islander",
      "Unknown"
   )
age_levels <- c("<18","18-24","25-44","45-64" ,"65+","Unknown")

names(shooting_raw) <- tolower(names(shooting_raw))
shooting <- shooting_raw %>%
   rename(time = occur_time,
          date = occur_date,
          is_murder = statistical_murder_flag) %>%
   mutate(is_murder = factor(is_murder,labels=c("Wounded","Murdered"))) %>% 
   mutate(date = as.Date(date,format = "%m/%d/%Y")) %>%
   mutate_if(is_character,str_to_title) %>%
   #turn all strings to factors
   mutate_if(is_character,as_factor) %>%
   mutate(precinct=as.factor(precinct)) %>%
   mutate(vic_sex=fct_explicit_na(vic_sex,na_level="U")) %>% 
   mutate(perp_sex=fct_explicit_na(perp_sex,na_level="U")) %>% 
   mutate_at(vars(contains("race")),factor,levels=race_levels) %>%
   mutate_at(vars(contains("age")),factor,levels=age_levels) %>%
   mutate_if(is.factor,fct_explicit_na,na_level="Unknown") %>%
   {.}

loc_levels <- shooting %>%
   group_by(location_desc) %>%
   count() %>% arrange(desc(n)) %>%
   pull(location_desc) %>%
   as.character()

shooting <- shooting %>% mutate(location_desc=factor(location_desc,levels = loc_levels))
```

```{r}
# -----------------------------------
# Shooting Trends
shooting %>%
   mutate(year=year(date)) %>%
   group_by(year,is_murder) %>% tally %>%
   ggplot(aes(year,n,fill=is_murder)) + geom_col() +
   scale_fill_discrete(name="") +
      labs(title = "Safer and Safer",
        subtitle = "NYC Shootings 2003 to 2019-09",
        caption = "source:NYPD Compstat",
        x = "",
        y = "Count")

```

```{r}
# -------------------------------------------------------
# Wrong place, wrong time
shooting %>% mutate(hour = hour(time)) %>%
   group_by(hour) %>%
   ggplot(aes(hour)) + geom_bar()  +
   labs(title = "The Midnight Hour",
        subtitle = "NYC Shootings 2003 to 2019-09",
        caption = "source:NYPD Compstat",
        x = "Hour of the Day",
        y = "Count")
```

```{r,fig.height=8,fig.width=8}
# rank most dangerous spots and turn to factor level
shooting %>% mutate(hour = hour(time)) %>%
   group_by(hour,location_desc) %>%
   tally() %>%
   ggplot(aes(hour,location_desc,fill=n)) + geom_tile() +
   # note log gradient fill
   scale_fill_gradient(trans = "log",breaks = c(1,10,100,500),name="Count",) +
   labs(title = "Wrong Place, Wrong Time",
        subtitle = "NYC Shootings 2003 to 2019-09",
        caption = "source:NYPD Compstat")
```


```{r message=FALSE, warning=FALSE}
# -------------------------------------------------------

# make new sf object with shooting location
shooting_detail <- shooting %>% 
   st_as_sf(coords = c("longitude","latitude"),
            crs="+proj=longlat +datum=WGS84 +no_defs",
            na.fail=FALSE)

precinct_summary <- shooting %>% 
   group_by(precinct) %>% 
   tally(name="shootings") 

precincts <- st_read(here::here("/data/police precincts.geojson")) %>% 
   left_join(precinct_summary, by = "precinct") %>% 
   mutate(shootings_per_sq_mi = round(shootings/as.numeric(shape_area)/10,1)) %>% 
   select(-shape_area,-shape_leng)

mapview::mapview(precincts, 
                 zcol = "shootings",
                 popup = popupTable(precincts,
                                    feature.id = FALSE,
                                    row.numbers = FALSE,
                                    zcol = c("precinct",
                                             "shootings",
                                             "shootings_per_sq_mi"))) +
   mapview::mapview(shooting_detail,
                    popup = popupTable(shooting_detail,
                                       feature.id = FALSE,
                                       row.numbers = FALSE
                                       
                    ))
```

## Who kills Who
What are the demographics of perpetrators and victims.  Incidents where demographic information is unknown are removed.  This takes out about 40% of all the incidents.

```{r}
shooting %>% ggplot(aes(perp_age_group,fill=perp_age_group)) + geom_bar()+
      labs(title = "The Identity of many Perps is Unknown at the time of the Incident",
        subtitle = "NYC Shootings 2003 to 2019-09",
        caption = "source:NYPD Compstat")
```



```{r}
# -------------------------------------------------------


# Things to make alluvial plots more readable
# remove unknown demographics
shooting_known <- shooting %>% 
   filter_at(vars(contains("perp")),all_vars(. != "Unknown")) %>% 
   filter_at(vars(contains("vic")),all_vars(. != "Unknown"))

#combine Hispanic subsets
shooting_known$vic_race <- fct_collapse(shooting_known$vic_race,
                                        Hispanic =c("Black Hispanic","White Hispanic"))
shooting_known$perp_race <- fct_collapse(shooting_known$perp_race,
                                        Hispanic =c("Black Hispanic","White Hispanic"))

shot_tally <- shooting_known %>% group_by(perp_race,vic_race) %>%
   tally() %>%
   arrange(desc(n)) %>%
   {.}

shot_tally %>% ggplot(aes(y=n,axis1=perp_race,axis2=vic_race)) + 
   geom_alluvium(width = 1/12) + 
  geom_stratum(width = 1/12, fill = "black", color = "grey") +
  geom_label(stat = "stratum", infer.label = TRUE) +
  scale_x_discrete(limits = c("perp_race", "vic_race"), expand = c(.05, .05))
```

```{r}
shot_tally <- shooting_known %>% 
   filter(perp_age_group != "Unknown") %>% 
   group_by(perp_age_group,vic_age_group) %>%
   tally() %>%
   arrange(desc(n)) %>%
   {.}


shot_tally %>% ggplot(aes(y=n,axis1=perp_age_group,axis2=vic_age_group)) + 
   geom_alluvium(width = 1/12) + 
  geom_stratum(width = 1/12, fill = "black", color = "grey") +
  geom_label(stat = "stratum", infer.label = TRUE) +
  scale_x_discrete(limits = c("perp_sex", "vic_sex"), expand = c(.05, .05))

```

```{r}
shot_tally <- shooting_known %>% 
   group_by(perp_sex,vic_sex) %>%
   tally() %>%
   arrange(desc(n)) %>%
   {.}
shot_tally %>% ggplot(aes(y=n,axis1=perp_sex,axis2=vic_sex)) + 
   geom_alluvium(width = 1/12) + 
  geom_stratum(width = 1/12, fill = "black", color = "grey") +
  geom_label(stat = "stratum", infer.label = TRUE) +
  scale_x_discrete(limits = c("perp_sex", "vic_sex"), expand = c(.05, .05))

```

